Generate doc
ScribeLabsAI/ScribeMi pull request #144
Opened 2023-12-06 17:21 UTC by ailinvenerus

**Done:**
- Create docstring
- Update requirements.txt

**To do:**
- Create pipeline to publish to docs repo

2023-12-07 12:09 UTC, ailinvenerus commented on .github/workflows/update-doc.yml
> +          GH_TOKEN: ${{ secrets.WEBSITE_GITHUB_TOKEN }}
It's the same token we used in ScribeAuth to update the doc https://github.com/ScribeLabsAI/ScribeAuth/blob/master/.github/workflows/update-doc.yml

2023-12-07 13:04 UTC, EHadoux commented
> > lgtm provided Alex's issues are resolved. Ideally we could also see the generated .md with the PR.
> 
> I added the _docs_ folder (with the .md) in .gitignore, should I delete that line and add the files?

Not sure, that might mess up the build/deployment. Just drop it in the PR in a message as an attachment

2023-12-07 13:08 UTC, ailinvenerus commented
The .md created when generating the doc:
[reference.md](https://github.com/ScribeLabsAI/ScribeMi/files/13600443/reference.md)

2023-12-07 17:29 UTC, ailinvenerus commented
new version: [reference.md](https://github.com/ScribeLabsAI/ScribeMi/files/13603170/reference.md)

2023-12-07 17:35 UTC, EHadoux requested changes

2023-12-07 17:35 UTC, EHadoux commented on scribemi/ScribeMi.py
> +    items: List[Item]
Are we not writing documentation for these?

2023-12-08 10:34 UTC, alexbostock reviewed
I'm happy with everything once Emmanuel's comments are resolved.

Some nitpicks about words, but we have another ticket for that: makes sense to nitpick all the docs together as part of the other ticket

2023-12-08 16:48 UTC, EHadoux approved these changes

2023-12-08 16:48 UTC, merged